---
name: snmpd build
description: Build snmpd

runs:
  using: "composite"
  steps:
    - run: |
        echo ::group::Download the source
        sudo apt-get install snmpd
        echo ::endgroup::
      shell: bash

    - run: |
        echo ::group::Extract the contents
        sudo apt-get install snmp
        echo ::endgroup::
      shell: bash

    # - run: |
    #     echo ::group::Start snmpd service
    #     sudo systemctl start snmpd
    #     echo ::endgroup::
    #   shell: bash

    - run: |
        echo ::group::echo snmpd conf status
        sudo cat /etc/snmp/snmpd.conf
        echo ::endgroup::
      shell: bash

    # - run: |
    #     echo ::group::Check snmpd service status
    #     sudo systemctl status snmpd.service
    #     echo ::endgroup::
    #   shell: bash

    - run: |
        echo ::group::Check snmpd service logs
        sudo journalctl -xeu snmpd.service
        echo ::endgroup::
      shell: bash
