name: netsnmp build
description: Build netsnmp

inputs:
  netsnmp-version:
    description: the netsnmp version
    required: true

  python-version:
    description: the python version
    required: true

runs:

  using: "composite"
  steps:
  
    - name: Download the netsnmp source
      run: wget http://sourceforge.net/projects/net-snmp/files/net-snmp/${{ inputs.netsnmp-version }}/net-snmp-${{ inputs.netsnmp-version }}.tar.gz
      shell: bash

    - name: Extract the contents
      run: tar -xvf net-snmp-${{ inputs.netsnmp-version }}.tar.gz
      shell: bash

    - name: Install dependancies
      run: sudo apt-get install libperl-dev
      shell: bash

    - name: Configure the source
      run: ./configure --with-python-modules --libdir=/usr/lib64 --enable-shared
      shell: bash
      working-directory: net-snmp-${{ inputs.netsnmp-version }}

    - name: Make snmp
      run: make
      shell: bash
      working-directory: net-snmp-${{ inputs.netsnmp-version }}

    - name: Install netsnmp
      run: sudo make install
      shell: bash
      working-directory: net-snmp-${{ inputs.netsnmp-version }}

    - name: Confrim version 
      run: snmpget --version
      shell: bash

    - name: Build the python bindings
      run: python${{ inputs.python-version }} setup.py build
      shell: bash
      working-directory: net-snmp-${{ inputs.netsnmp-version }}/python

    - name: Ensure setuptools is installed for sudo
      run: sudo env "PATH=$PATH" python -m pip install setuptools
      shell: bash

    - name: Install the python bindings
      run: sudo env "PATH=$PATH" python setup.py install
      shell: bash
      working-directory: net-snmp-${{ inputs.netsnmp-version }}/python
    
    - name: Confim python binding available
      run: python${{ inputs.python-version }} -c 'import netsnmp'
      shell: bash

