---
name: netsnmp build
description: Build netsnmp

inputs:
  netsnmp-version:
    description: the netsnmp version
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        echo ::group::Download the source
        wget http://sourceforge.net/projects/net-snmp/files/net-snmp/${{ inputs.netsnmp-version }}/net-snmp-${{ inputs.netsnmp-version }}.tar.gz 2>&1
        echo ::endgroup::
      shell: bash

    - run: |
        echo ::group::Extract the contents
        tar -xvf net-snmp-${{ inputs.netsnmp-version }}.tar.gz
        echo ::endgroup::
      shell: bash

    - run: |
        echo ::group::Install dependancies
        sudo apt-get install libperl-dev
        pip install --upgrade setuptools
        echo ::endgroup::
      shell: bash

    - run: |
        echo ::group::Configuring the source
        ./configure --with-python-modules --enable-shared --with-systemd --prefix=/usr/local --sysconfdir=/usr/local/etc --datadir=/usr/local/share --with-persistent-directory=/var/lib/snmp
        echo ::endgroup::
      shell: bash
      working-directory: net-snmp-${{ inputs.netsnmp-version }}

    - run: |
        echo ::group::Running make
        make
        echo ::endgroup::
      shell: bash
      working-directory: net-snmp-${{ inputs.netsnmp-version }}

    - run: |
        echo ::group::Installing snmp
        sudo make install
        echo ::endgroup::
      shell: bash
      working-directory: net-snmp-${{ inputs.netsnmp-version }}

    - run: |
        echo ::group::Add the netsnmp library install path to ldconfig
        sudo ldconfig -v | grep snmp #echo "/usr/local/lib" | sudo tee /etc/ld.so.conf.d/netsnmp.conf &&
        echo ::endgroup::
      shell: bash

    - run: |
        echo ::group::Confirm version
        snmpget --version
        echo ::endgroup::
      shell: bash

    - run: |
        echo ::group::Build the python bindings
        python setup.py build
        echo ::endgroup::
      shell: bash
      working-directory: net-snmp-${{ inputs.netsnmp-version }}/python

    - run: |
        echo ::group::Ensure setuptools is installed for sudo
        sudo env "PATH=$PATH" python -m pip install setuptools
        echo ::endgroup::
      shell: bash

    - run: |
        echo ::group::Install the python bindings
        sudo env "PATH=$PATH" python setup.py install
        echo ::endgroup::
      shell: bash
      working-directory: net-snmp-${{ inputs.netsnmp-version }}/python

    - run: |
        echo ::group::Confirm the python bindings are available
        python -c 'import netsnmp'
        echo ::endgroup::
      shell: bash
