---
name: Collection integration tests
on: [push, pull_request]  # yamllint disable-line rule:truthy
jobs:
  deps:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        netsnmp-version: [5.9.4]
        python-version: [3.11.5]
    name: "Integration Test"  # : netsnmp ${{ matrix.netsnmp-version }} - python ${{ matrix.python-version }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Download and build netsnmp ${{ matrix.netsnmp-version }} for python ${{ matrix.python-version }}
        uses: ./.github/actions/netsnmp
        with:
          netsnmp-version: ${{ matrix.netsnmp-version }}

      - name: Enable snmpd (test)
        uses: ./.github/actions/snmpd

      - name: Prepare the collection
        id: prepare_collection
        uses: ./.github/actions/ansible_collection

      - name: Install navigator
        run: pip3 install -r test-requirements.txt

      - name: Run integration tests
        run: ansible-navigator
        env:
          ANSIBLE_VERBOSITY: 4
          ANSIBLE_NAVIGATOR_APP: run
          ANSIBLE_NAVIGATOR_MODE: stdout
          ANSIBLE_NAVIGATOR_LOG_FILE: gh-action-logs/navigator-integration.log
          ANSIBLE_NAVIGATOR_LOG_LEVEL: debug
          ANSIBLE_NAVIGATOR_PLAYBOOK: tests/integration/integration_runner.yaml
          ANSIBLE_NAVIGATOR_PLAYBOOK_ARTIFACT_SAVE_AS: gh-action-logs/navigator-integration-artifact.json
          ANSIBLE_NAVIGATOR_INVENTORIES: tests/integration/integration_inventory.yaml
          ANSIBLE_NAVIGATOR_EXECUTION_ENVIRONMENT: False  # yamllint disable-line rule:truthy
          COLLECTION_NAMESPACE: ${{ steps.prepare_collection.outputs.collection_namespace }}
          COLLECTION_NAME: ${{ steps.prepare_collection.outputs.collection_name }}
          INTEGRATION_TESTS_PATTERN: "snmp_*"

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: navigator-artifacts
          path: gh-action-logs/
